const videoData = [
  {
    id: 1,
    videoUrl: "https://vz-c948731a-e8d.b-cdn.net/54e0522c-b4be-4c79-9107-01e3905e6222/playlist.m3u8",
    category: "Kaballah",
    poster: "https://vz-c948731a-e8d.b-cdn.net/54e0522c-b4be-4c79-9107-01e3905e6222/thumbnail_79ec4206.jpg",
    thumbnail: "https://vz-c948731a-e8d.b-cdn.net/54e0522c-b4be-4c79-9107-01e3905e6222/preview.webp",
    title: "one",
    rabbi: "Name of Rabbi",
    durration: 5300,
    date: "1 month ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 5,
    numViews: 120,
    numComments: 47,
  },
  {
    
    id: 2,
    videoUrl: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/playlist.m3u8",
    category: "Kaballah",
    poster: "https://vz-c948731a-e8d.b-cdn.net/54e0522c-b4be-4c79-9107-01e3905e6222/thumbnail_70941c64.jpg",
    thumbnail: "https://vz-c948731a-e8d.b-cdn.net/54e0522c-b4be-4c79-9107-01e3905e6222/preview.webp",
    title: "two",
    rabbi: "Name of Rabbi",
    durration: 5300,
    date: "1 month ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 5,
    numViews: 120,
    numComments: 47,
  },
  {
    id: 3,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222886-8b8b-213dff612e97/playlist.m3u8",
    category: "Kaballah",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/thumbnail.jpg",
    thumbnail: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/preview.webp",
    title: "video title name goes here part video title name goes here part 4video title name goes here part 4 4",
    rabbi: "Name of Rabbi",
    durration: 5300,
    date: "1 month ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 5,
    numViews: 120,
    numComments: 47,
  },
  {
    id: 4,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    category: "Kaballah",
    poster: "https://vz-c948731a-e8d.b-cdn.net/54e0522c-b4be-4c79-9107-01e3905e6222/thumbnail_79ec4206.jpg",
    thumbnail: "https://vz-c948731a-e8d.b-cdn.net/54e0522c-b4be-4c79-9107-01e3905e6222/preview.webp",
    title: "video title name goes here part video title name goes here part 4video title name goes here part 4 4",
    rabbi: "Name of Rabbi",
    durration: 5300,
    date: "1 month ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 5,
    numViews: 120,
    numComments: 47,
  },
  {
    id: 5,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "halakha",
    title: "video title 1",
    rabbi: "Name of Rabbi",
    durration: 5200,
    date: "5 days ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 8,
    numViews: 150,
    numComments: 40,
  },
  {
    id: 6,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "mussar",
    title: "video title 2",
    rabbi: "Name of Rabbi2",
    durration: 5500,
    date: "3 months ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 3,
    numViews: 90,
    numComments: 99,
  },
  {
    id: 7,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "shalom baith",
    title: "video title name 1",
    rabbi: "Name of Rabbi22",
    durration: 6100,
    date: "2 months ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 12,
    numViews: 400,
    numComments: 110,
  },
  {
    id: 8,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "khinukh yeladim",
    title: "video title name 2",
    rabbi: "Name of Rabbi22",
    durration: 5800,
    date: "4 months ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 6,
    numViews: 110,
    numComments: 33,
  },
  {
    id: 9,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "teffilah",
    title: "video title name goes 3",
    rabbi: "Name of Rabbi11",
    durration: 6200,
    date: "6 months ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 15,
    numViews: 500,
    numComments: 120,
  },
  {
    id: 10,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "Q&A",
    title: "video title name goes 2",
    rabbi: "Name of Rabbi11",
    durration: 5700,
    date: "1 month ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 9,
    numViews: 210,
    numComments: 50,
  },
  {
    id: 11,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "khizuk",
    title: "video title name goes 1",
    rabbi: "Name of Rabbi10",
    durration: 5300,
    date: "2 weeks ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 11,
    numViews: 250,
    numComments: 65,
  },
  {
    id: 12,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "emunah",
    title: "video title name goes 5",
    rabbi: "Name of Rabbi9",
    durration: 5600,
    date: "5 days ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 13,
    numViews: 310,
    numComments: 90,
  },
  {
    id: 13,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "tsuva",
    title: "video title name goes here 2",
    rabbi: "Name of Rabbi",
    durration: 5900,
    date: "3 months ago8",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 14,
    numViews: 450,
    numComments: 100,
  },
  {
    id: 14,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "khagim",
    title: "video title name goes here 1",
    rabbi: "Name of Rabbi7",
    durration: 6200,
    date: "1 month ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 10,
    numViews: 300,
    numComments: 70,
  },
  {
    id: 15,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "shalom baith",
    title: "video title name goes here (eg. this is a video title",
    rabbi: "Name of Rabbi7",
    durration: 5500,
    date: "2 months ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 15,
    numViews: 400,
    numComments: 85,
  },
  {
    id: 16,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "khinukh yeladim",
    title: "video title name goes here (eg.deo title",
    rabbi: "Name of Rabbi7",
    durration: 5800,
    date: "3 weeks ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 12,
    numViews: 270,
    numComments: 60,
  },
  {
    id: 17,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "teffilah",
    title: "video title name goes here (eg. this isle",
    rabbi: "Name of Rabbi6",
    durration: 6100,
    date: "1 month ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 9,
    numViews: 220,
    numComments: 50,
  },
  {
    id: 18,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "Q&A",
    title: "video title name goes here (eg. this iasdasds a video title",
    rabbi: "Name of Rabbi5",
    durration: 5900,
    date: "2 months ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 14,
    numViews: 350,
    numComments: 90,
  },
  {
    id: 19,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "khizuk",
    title: "video title name goes here (eg. this iasdasdass a video title",
    rabbi: "Name of Rabbi4",
    durration: 5600,
    date: "1 week ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 8,
    numViews: 180,
    numComments: 40,
  },
  {
    id: 20,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "emunah",
    title: "video title name goes here (eg. this isasdasda a video title",
    rabbi: "Name of Rabbi4",
    durration: 6000,
    date: "3 months ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 13,
    numViews: 330,
    numComments: 75,
  },
  {
    id: 21,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "tsuva",
    title: "video title name goes here (easdasdg. this is a video title",
    rabbi: "Name of Rabbi3",
    durration: 5400,
    date: "4 months ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 11,
    numViews: 290,
    numComments: 55,
  },
  {
    id: 22,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "talmud",
    title: "video title name goes here (easdasdg. this is a video title",
    rabbi: "Name of Rabbi2",
    durration: 6200,
    date: "5 months ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 16,
    numViews: 380,
    numComments: 95,
  },
  {
    id: 23,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "mishna",
    title: "video title name goes here (easdasdg. this is a video title",
    rabbi: "Name of Rabbi2",
    durration: 5700,
    date: "1 month ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 17,
    numViews: 410,
    numComments: 100,
  },
  {
    id: 24,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "parasha",
    title: "one",
    rabbi: "Name of Rabbi1",
    durration: 6300,
    date: "3 weeks ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 9,
    numViews: 240,
    numComments: 60,
  },
  {
    id: 25,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "shabbat",
    title: "two",
    rabbi: "Name of Rabbi3",
    durration: 5800,
    date: "2 months ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 13,
    numViews: 320,
    numComments: 80,
  },
  {
    id: 26,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "halakha",
    title: "three",
    rabbi: "Name of Rabbi5",
    durration: 5400,
    date: "4 months ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 11,
    numViews: 290,
    numComments: 55,
  },
  {
    id: 27,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "mussar",
    title: "four",
    rabbi: "Name of Rabbi",
    durration: 6000,
    date: "1 month ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 14,
    numViews: 330,
    numComments: 75,
  },
  {
    id: 28,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "khagim",
    title: "video title name goes here (eg. this is a video title",
    rabbi: "Name of Rabbi1",
    durration: 5700,
    date: "2 months ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 12,
    numViews: 310,
    numComments: 70,
  },
  {
    id: 29,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "shalom baith",
    title: "video title name goes here (eg. this is a video title",
    rabbi: "Name of Rabbi29",
    durration: 6300,
    date: "3 months ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 16,
    numViews: 400,
    numComments: 90,
  },
  {
    id: 30,
    videoUrl: "54e0522c-b4be-4c79-9107-01e3905e6222",
    poster: "https://vz-c948731a-e8d.b-cdn.net/6b7698f5-e890-4886-8b8b-213dff612e97/poster.jpg",
        category: "khinukh yeladim",
    title: "video title name goes here (eg. this is a video title",
    rabbi: "Name of Rabbi30",
    durration: 6000,
    date: "1 week ago",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non tempus lectus, ac tristique velit. Praesent condimentum neque sed arcu fermentum faucibus. Morbi in justo sit amet magna ullamcorper condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec blandit congue venenatis. In hac habitasse platea dictumst. Nunc ut augue ut elit mollis blandit. Suspendisse sit amet sem consequat, malesuada sem mollis, pellentesque tortor.",
    numLikes: 9,
    numViews: 220,
    numComments: 50,
  },
];
export default videoData;
